Replace tree widget
iTwin/viewer pull request #36
Opened 2021-08-09 18:51 UTC by spap975

I removed the Tree Widget from default DefaultFrontstage and put the widget in useUiProviders.

2021-08-09 19:00 UTC, aruniverse commented on packages/modules/viewer-react/src/hooks/useUiProviders.tsx
> +import { TreeWidgetUiItemsProvider } from "@bentley/tree-widget-react/lib/components/TreeWidgetUiItemsProvider";
lets wait for https://github.com/imodeljs/viewer-components-react/pull/126

2021-08-09 19:03 UTC, aruniverse commented on packages/modules/viewer-react/src/hooks/useUiProviders.tsx
> +    const defaultProviders: UiItemsProvider[] = [
currently we have a way for users to toggle this off, via the defaultUiConfig.hideTreeView, should probably check that here

2021-08-09 20:08 UTC, kckst8 requested changes

2021-08-09 20:08 UTC, kckst8 commented on packages/modules/viewer-react/src/hooks/useUiProviders.tsx
> +    const _uiProviders = uiProviders
I would not use an underscore here. Instead rename the arg to something like "customUiProviders" and keep the const as simply "uiProviders"

2021-08-10 17:12 UTC, aruniverse commented on common/changes/@itwin/viewer-react/replaceTreeWidget_2021-08-09-19-51.json
> +      "type": "patch"
let make this a minor bump here since we bumped the tree-widget ver
```suggestion
      "type": "minor"
```

2021-08-10 17:12 UTC, aruniverse commented on packages/modules/viewer-react/package.json
> +    "@bentley/tree-widget-react": "^1.4.2",
no lockfile changes?

2021-08-10 17:38 UTC, aruniverse commented on packages/modules/viewer-react/src/hooks/useUiProviders.tsx
> +  defaultUiConfig?: ItwinViewerUi
dont you need to pass in the defaultUiConfig in IModelLoader?

2021-08-10 17:38 UTC, aruniverse commented on packages/modules/viewer-react/src/hooks/useUiProviders.tsx
> +    if (defaultUiConfig?.hideTreeView !== true) {
```suggestion
    if (!!defaultUiConfig?.hideTreeView) {
```

2021-08-10 17:38 UTC, aruniverse commented on packages/modules/viewer-react/src/hooks/useUiProviders.tsx
> +  defaultUiConfig?: ItwinViewerUi
todo: later on need to figure out how to correctly pass options to these uiProviders

2021-08-10 17:47 UTC, aruniverse commented on packages/modules/viewer-react/src/hooks/useUiProviders.tsx
> +    if (!!defaultUiConfig?.hideTreeView) {
sorry i told you to add one more ! than needed

2021-08-10 17:47 UTC, aruniverse commented on packages/modules/viewer-react/src/hooks/useUiProviders.tsx
> +    if (!!defaultUiConfig?.hideTreeView) {
test it out

2021-08-10 18:01 UTC, aruniverse commented on common/changes/@itwin/viewer-react/replaceTreeWidget_2021-08-09-19-51.json
> +      "comment": "Updated tree widget to use the UiProvider instead of the widget control",
```suggestion
      "comment": "Updated base viewer to use the @bentley/tree-widget-react UiProvider instead of the widget control",
```

2021-08-10 18:03 UTC, aruniverse approved these changes

2021-08-16 13:37 UTC, kckst8 approved these changes

2021-08-16 13:37 UTC, merged