Fixed issues related to viewstate and connections
iTwin/viewer pull request #44
Opened 2021-09-07 20:06 UTC by StefanRetief

This fixes the issues related to Viewstate and connection changing.

- Changing imodel connections (contextid, imodelid, snapshot) will result in the viewstate being cleared and a default viewstate being fetched and applied.
- Rendering a view will only occur when both a viewstate and a connection has been established or a frontstage that does not require a connection has been provided.
- Viewstates created for the blank viewer will be more unopinionated, resulting in always giving a top-down view. Invalid ```lookAt``` properties will result in a console error. (Please advise).
- (Regression) Connections will be closed each time connections change.

It appears that there is currently a race condition with setting a frontstage provider. It appears that when the ```IModelViewer``` is loading, the ```FrontstageManager.setActiveFrontstage``` method cannot be called, as the desired frontstage will not be applied. Waiting for the the component to finish rendering its children (async driven), and then calling the ```setActiveFrontstage``` method will give the desired result.

2021-09-08 13:50 UTC, kckst8 reviewed
Added a comment. Other code looks ok but I will test it today. 

I'm in mid refactor and making some changes in this area as well. I think these changes will patch some larger issues in the IModelLoader component. There are too many asynchronous tasks that are related with potential collisions and/or improper state management.

2021-09-08 13:50 UTC, kckst8 commented on packages/modules/viewer-react/src/components/iModel/IModelViewer.tsx
> +      setImmediate(
unfortunately, we cant use this. Lack of browser support and no plans to standardize:

https://caniuse.com/setimmediate

https://developer.mozilla.org/en-US/docs/Web/API/Window/setImmediate

2021-09-08 13:50 UTC, kckst8 commented on packages/modules/viewer-react/src/tests/components/iModel/IModelViewer.test.tsx
> +const flushPromises = () => new Promise(setImmediate);
same here

2021-09-08 16:46 UTC, kckst8 requested changes
Changing the iModel id causes an error when closing the connection:

![image](https://user-images.githubusercontent.com/6283674/132550695-da827be0-896b-4497-91e7-62c5eef4521b.png)

You can reproduce using the "Switch iModel" button in the auth config route in the web viewer test app

2021-09-30 20:26 UTC, kckst8 reviewed
seems like a lot of file changes. A lot of scss files have duplicate copyright headers. Assuming from a merge commit? Possibly line ending/encoding?

2021-09-30 20:28 UTC, StefanRetief commented
> seems like a lot of file changes. A lot of scss files have duplicate copyright headers. Assuming from a merge commit? Possibly line ending/encoding?

Yeah, probably from the latest merge with master. I thought I caught all of them, but I'll resolve the last few.

2021-09-30 23:09 UTC, kckst8 approved these changes

2021-10-01 13:47 UTC, merged